### ISSUE TITLE
2024 [SIGMOD] Origin-Destination Travel Time Oracle for Map-based Services

### ISSUE THREAD

**Issue by shenzekai** [yyysjz1997/Awesome-TimeSeries-SpatioTemporal-Diffusion-Model#1]
Hi, there is a paper "Origin-Destination Travel Time Oracle for Map-based Services" accepted by SIGMOD24, which used the diffusion model for Travel Time Estimation（OD-Based）
Link：https://dl.acm.org/doi/abs/10.1145/3617337

**Comment by yyysjz1997** [comment]
Thanks so much! I have added your paper to this Repo.😊
