### ISSUE TITLE
Diff-RNTraj: A Structure-aware Diffusion Model for Road Network-constrained Trajectory Generation

### ISSUE THREAD

**Issue by shenzekai** [yyysjz1997/Awesome-TimeSeries-SpatioTemporal-Diffusion-Model#2]
Hi, there is a paper "**Diff-RNTraj: A Structure-aware Diffusion Model for Road Network-constrained Trajectory Generation**" on arXiv, which used the diffusion model for **trajectory generation**.
Link：[https://arxiv.org/abs/2402.07369](https://arxiv.org/abs/2402.07369)

**Comment by yyysjz1997** [comment]
> Hi, there is a paper "**Diff-RNTraj: A Structure-aware Diffusion Model for Road Network-constrained Trajectory Generation**" on arXiv, which used the diffusion model for **trajectory generation**. Link：https://arxiv.org/abs/2402.07369

Thanks! I have added it to the Repo.
