### ISSUE TITLE
[Question] Is DiffTAD [83] in the Uncondition category in the review?

### ISSUE THREAD

**Issue by Moxie1337** [yyysjz1997/Awesome-TimeSeries-SpatioTemporal-Diffusion-Model#3]
Hi, I was wondering if the article DiffTAD [83] is in the category condition diffusion? Although this article does not show ε_θ(x_t, c, t) in the training formula for the diffusion model, in Figure 3 he explains the use of Decoder to take concatenated state embeddings to learn the reverse diffusion process with the variational lower bound.I am a little bit confused about this part, can you answer my confusion, thanks a lot!

**Comment by yyysjz1997** [comment]
> Hi, I was wondering if the article DiffTAD [83] is in the category condition diffusion? Although this article does not show ε_θ(x_t, c, t) in the training formula for the diffusion model, in Figure 3 he explains the use of Decoder to take concatenated state embeddings to learn the reverse diffusion process with the variational lower bound.I am a little bit confused about this part, can you answer my confusion, thanks a lot!

Hey. Thanks so much for your interest. From the DiffTAD paper's description, there is no more information/guidance for the reverse process. So maybe it should be an unconditional diffusion unless we could see the public code or more detailed information about it. Feel free to discuss if you have more info!

**Comment by Moxie1337** [comment]
I am glad to get your reply! I understand how to distinguish whether it's a conditional/unconditional diffusion model or not - to have classifier(or free) gudiance in the paper's formulae or conditional information (e.g. labels, embedding information in text or low-dimensional images, etc.) in the denoised process. The mere presence of a textual description is not enough to classify it as a conditional diffusion model. Surprisingly the [github link](https://github.com/Psychic-DL/DiffTAD) given in this paper doesn't seem to have the appropriate code!

**Comment by yyysjz1997** [comment]
> I am glad to get your reply! I understand how to distinguish whether it's a conditional/unconditional diffusion model or not - to have classifier(or free) gudiance in the paper's formulae or conditional information (e.g. labels, embedding information in text or low-dimensional images, etc.) in the denoised process. The mere presence of a textual description is not enough to classify it as a conditional diffusion model. Surprisingly the [github link](https://github.com/Psychic-DL/DiffTAD) given in this paper doesn't seem to have the appropriate code!

Hi, Maybe just wait their public code is the first choice now. And if there is an update, we can discuss further.

**Comment by Moxie1337** [comment]
Ok, thanks for answering my question :)
