### ISSUE TITLE
Wrong official code for ControlTraj

### ISSUE THREAD

**Issue by CharlotteE67** [yyysjz1997/Awesome-TimeSeries-SpatioTemporal-Diffusion-Model#4]
> ControlTraj: Controllable Trajectory Generation with Topology-Constrained Diffusion Model, in ArXiv 2024. [[paper](https://arxiv.org/pdf/2404.15380)] [[official-code](https://github.com/aimiokab/MISR-S2)]

In part [diffusion-model-for-spatio-temporal-data](https://github.com/yyysjz1997/Awesome-TimeSeries-SpatioTemporal-Diffusion-Model?tab=readme-ov-file#diffusion-model-for-spatio-temporal-data), the official code repository is wrong for ControlTraj. And it seems that there is no official code for it now.

**Comment by yyysjz1997** [comment]
> > ControlTraj: Controllable Trajectory Generation with Topology-Constrained Diffusion Model, in ArXiv 2024. [[paper](https://arxiv.org/pdf/2404.15380)] [[official-code](https://github.com/aimiokab/MISR-S2)]
> 
> In part [diffusion-model-for-spatio-temporal-data](https://github.com/yyysjz1997/Awesome-TimeSeries-SpatioTemporal-Diffusion-Model?tab=readme-ov-file#diffusion-model-for-spatio-temporal-data), the official code repository is wrong for ControlTraj. And it seems that there is no official code for it now.

Updated. Thanks for your feedback.
